# permissions for end users to edit adnconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: adnconfig-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: app-defined-networks
    app.kubernetes.io/part-of: app-defined-networks
    app.kubernetes.io/managed-by: kustomize
  name: adnconfig-editor-role
rules:
- apiGroups:
  - api.core.adn.io
  resources:
  - adnconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.core.adn.io
  resources:
  - adnconfigs/status
  verbs:
  - get
