# permissions for end users to view adnconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: adnconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: app-defined-networks
    app.kubernetes.io/part-of: app-defined-networks
    app.kubernetes.io/managed-by: kustomize
  name: adnconfig-viewer-role
rules:
- apiGroups:
  - api.core.adn.io
  resources:
  - adnconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.core.adn.io
  resources:
  - adnconfigs/status
  verbs:
  - get
