---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - api.core.adn.io
  resources:
  - adnconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.core.adn.io
  resources:
  - adnconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - api.core.adn.io
  resources:
  - adnconfigs/status
  verbs:
  - get
  - patch
  - update
