apiVersion: v1
kind: Service
metadata:
  name: mrpc-client
spec:
  clusterIP: 10.96.88.88
  ports:
  - name: mrpc-client
    port: 7878
    targetPort: 7878
  selector:
    app: mrpc-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mrpc-client
spec:
  replicas: 1
  template:
    metadata:
      name: mrpc-client
      labels:
        app: mrpc-client
    spec:
      hostNetwork: true
      hostIPC: true
      containers:
      - image: xzhu0027/phoenixos-rpc-echo
        imagePullPolicy: Always
        name: mrpc-client
        command: ["./rpc_echo_client2"]
        volumeMounts:
          - name: tmp-volume
            mountPath: /tmp/phoenix
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
          privileged: true
      volumes:
        - name: tmp-volume
          hostPath:
            path: /tmp/phoenix
            type: Directory
  selector:
    matchLabels:
      app: mrpc-client
---
